[project]
name = "data-processor"
version = "0.1.2"
description = ""
authors = [
    {name = "Marketa Solanikova",email = "solanikova@promark.sk"}
]
readme = "README.md"
requires-python = "~=3.12"
dependencies = [
    "boto3 (==1.40.8)",
    "pydantic-settings (==2.10.1)"
]

[tool.poetry]
name = "data-processor"
version = "0.1.2"
packages = [{ include = "data_processor", from = "src" }]

[tool.poetry.group.test.dependencies]
pytest = "8.4.1"


[tool.poetry.group.dist.dependencies]
pydantic-settings = "^2.10.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
